version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5191:5191"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://backend:5191/api
    ports:
      - "3000:80"
    depends_on:
      - backend